baseURL = '/'
languageCode = 'en-us'
title = 'Ahmad Alkadri'
theme = 'PaperMod'
disqusShortname = 'cahier-d-ahmad'

[Params]
    mainSections = ["posts"]
    github = "https://github.com/ahmad-alkadri"
    email = "ahmad.alkadri@outlook.com"
    opengraph = true
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:filename/"
