baseURL = '/'
languageCode = 'en-us'
title = 'Ahmad Alkadri'
theme = 'PaperModSelf'
publishDir = 'docs'
disqusShortName = 'ahmad-alkadri'
paginate = 5

[Params]
    mainSections = ["posts"]
    github = "https://github.com/ahmad-alkadri"
    email = "ahmad.alkadri@outlook.com"
    opengraph = true
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:filename/"

[taxonomies]
    category = "categories"
