baseURL = '/'
languageCode = 'en-us'
title = 'Ahmad Alkadri'
theme = 'PaperModSelf'
publishDir = 'docs'
disqusShortName = 'ahmad-alkadri'
paginate = 5

[Params]
    mainSections = ["posts"]
    github = "https://github.com/ahmad-alkadri"
    email = "ahmad.alkadri@outlook.com"
    opengraph = true
    dateFormat = "Mon, Jan 2, 2006"
    ShowCodeCopyButtons = true

[Params.homeInfoParams]
Title = "Welcome!"
Content = """
This is a personal website of mine. Here, I mostly blog. 
I blog about [a lot of things](/categories/), such as [coding](/categories/coding/), [tech](/categories/tech/),
a bit into some [personal projects](/categories/projects/) I'm doing or have done.
Sometimes, I write down [my thoughts](/categories/philosophy/) too.

+

For the last four years, I've been working at a startup called [LEKO LABS](https://lekolabs.com).
I started out as a thermal simulation engineer, doing mostly standardized building physics
calculations, but over time I've also built simulation apps, developed end-to-end manufacturing
tool, data services, REST API apps, and many more. MERN and FReMP stacks, complemented by Streamlit,
Rust, and Golang, are my jam.

+

These days, other than work, I'm more into doing some web app development, learning Japanese
(B1 level now), and reading books. If you want to reach me, feel free to send me some
[email](mailto:ahmad.alkadri@outlook.com) or connect with me on [LinkedIn](https://www.linkedin.com/in/alkadri).
Otherwise, feel free to [search and browse](/search) through my blog and leave comment if you want!
"""

[[Params.socialIcons]]
name = "Github"
url = "https://github.com/ahmad-alkadri"

[[Params.socialIcons]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/alkadri"

[[Params.socialIcons]]
name = "Email"
url = "mailto:ahmad.alkadri@outlook.com"

[Permalinks]
    post = "/:filename/"

[taxonomies]
    category = "categories"

[outputs]
home = ["HTML", "RSS", "JSON"]

[Params.fuseOpts]
location = 0
distance = 2000
threshold = 0.2
includeScore = true
includeMatches = true
keys = ["title", "content"]